### ISSUE TITLE
Should C be counted as a language?

### ISSUE THREAD

**Issue by rjmantilla76** [mua-uniandes/weekly-problems#1]
Most of the code in C compiles in C++ anyways and I believe there are no coders in Uniandes who program in C. Is it really worth it to make it a separate folder within each solution?

**Comment by ncardozo** [comment]
True...
But as with natural language, language shapes thoughts so thinking in C can provide a different perspective than thinking in C++.
While there may not be C programmers now, there is absolutely no reason why there shouldn't be. C is a nice skill to have under your belt, particularly if you want to do embedded systems or middleware (translate to the IoT). 
Why not to try it out?

**Comment by nonameable** [comment]
Maybe it is a good exercise by itself given the tools that the language gives you, the way it forces you to think. I remember I read these a long time ago: 
[https://www.joelonsoftware.com/2005/12/29/the-perils-of-javaschools-2/](https://www.joelonsoftware.com/2005/12/29/the-perils-of-javaschools-2/
)

[https://www.joelonsoftware.com/2005/01/02/advice-for-computer-science-college-students/](https://www.joelonsoftware.com/2005/01/02/advice-for-computer-science-college-students/
)
Joel presents arguments to learn and practice C, even if you plan to work with something else later
